tricycle_mobile_robot:
   joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

   steer_joint_controller:
      type: effort_controllers/JointPositionController
      joint: steer_joint
      pid: {p: 3000.0, i: 0.005, d: 100.0}

   speed_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: front_wheel_joint
      pid: {p: 2000.0, i: 0.00005, d: 0.001}
